### ISSUE TITLE
[Bug]  Transfer NFT window shows name/description from different NFT

### ISSUE THREAD

**Issue by RightSexyOrc** [Chia-Network/chia-blockchain-gui#1156] opened 2022-11-04 19:11 UTC
### What happened?

To reproduce with wallet with multiple NFT's in it:

1. click on the three dots at bottom right of an NFT in the NFTs tab
2. click on "Transfer NFT"
3. observe the name and description of the NFT
![Screenshot from 2022-11-04 19-08-06](https://user-images.githubusercontent.com/86175513/200056534-c64a37da-a181-432e-94d5-aab726f543b5.png)

### Version

1.6.1

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by paninaro** [comment] 2022-11-04 20:58
Thanks for the report. This is a likely dupe of #1154 but I'll keep it open since it's showing up in a different integration point.

**Comment by paninaro** [comment] 2023-02-16 21:02
Fixed in 1.7.0

**Closed by paninaro** 2023-02-16 21:02 UTC
Labels: bug
