### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'version')

### ISSUE THREAD

**Issue by wookie73** [Chia-Network/chia-blockchain-gui#2241] opened 2023-12-14 23:25 UTC
### What happened?

In the GUI went to plots.
Clicked on add plot.
Screen went blank momentarily.
Error message appeared.

Something went wrong
Error: Cannot read properties of undefined (reading 'version')
at webpack://@chia-network/gui/src/components/plot/add/PlotAddForm.tsx:92:29 defaultsForPlotter
at webpack://@chia-network/gui/src/components/plot/add/PlotAddForm.tsx:101:19 plotters[plotterName].version.split
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:167:136 Xh
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:290:336 Wk
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:280:388 uj
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:280:319 uj
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:280:179 uj
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:271:87 Ok
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:273:299 Dk
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:127:104 jg

### Version

Chia 2.1.2

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Cannot read properties of undefined (reading 'version')

URL
#/dashboard/plot/add

Stacktrace
at webpack://@chia-network/gui/src/components/plot/add/PlotAddForm.tsx:92:29 defaultsForPlotter
at webpack://@chia-network/gui/src/components/plot/add/PlotAddForm.tsx:101:19 plotters[plotterName].version.split
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:167:136 Xh
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:290:336 Wk
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:280:388 uj
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:280:319 uj
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:280:179 uj
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:271:87 Ok
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:273:299 Dk
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:127:104 jg
```

**Comment by ChiaMineJP** [comment] 2023-12-28 11:21
Duplicate of this issue.
https://github.com/Chia-Network/chia-blockchain-gui/issues/2245

This issue was already fixed and will be included in the next release.

**Closed by ChiaMineJP** 2023-12-28 11:21 UTC
Labels: bug
