### ISSUE TITLE
[BUG]The page could not render the content

### ISSUE THREAD

**Issue by abiaqiou** [Chia-Network/chia-blockchain-gui#361] opened 2021-05-07 10:36 UTC
Steps:
1. clone this repo
2. npm install
3. npm start

on localhost:3000 , the screen is blank.
open the developer tool, it shows
```javascript
Uncaught ReferenceError: global is not defined
    at vendors-node_modules_lingui_core_esm_index_js-node_modules_lingui_react_esm_index_js-node_mod-544695.js:1

Uncaught ReferenceError: global is not defined
    at main.js:68229
    at main.js:68723
    at main.js:68737
```

platform: win10 20H2
node version: 14.16.0
npm version: 6.14.11

**Comment by seeden** [comment] 2021-05-09 08:23
Duplicate of https://github.com/Chia-Network/chia-blockchain-gui/issues/299. PR already created

**Closed by seeden** 2021-05-09 08:23 UTC
