### ISSUE TITLE
Never-resolved spinners in "Your Farm Overview"

### ISSUE THREAD

**Issue by atomsymbol** [Chia-Network/chia-blockchain-gui#539] opened 2021-09-11 15:48 UTC
chia-blockchain-gui 041ac79be4af360d856a6527a4b8f4a074415a9a

The GUI is waiting for the following fields to be resolved, but they are never resolved:

- XCH Total Chia Farmed
- XCH Block Rewards
- XCH User Transaction Fees
- Last Height Farmed

![Screenshot_20210911_173705](https://user-images.githubusercontent.com/22368256/132953298-19019895-8aca-4e57-a511-7f71f01d85f4.png)

**Comment by jack60612** [comment] 2021-09-12 14:21
Looking into it

**Comment by jack60612** [comment] 2021-09-12 14:23
> chia-blockchain-gui [041ac79](https://github.com/Chia-Network/chia-blockchain-gui/commit/041ac79be4af360d856a6527a4b8f4a074415a9a)
> 
> The GUI is waiting for the following fields to be resolved, but they are never resolved:
> 
> * XCH Total Chia Farmed
> * XCH Block Rewards
> * XCH User Transaction Fees
> * Last Height Farmed
> 
> ![Screenshot_20210911_173705](https://user-images.githubusercontent.com/22368256/132953298-19019895-8aca-4e57-a511-7f71f01d85f4.png)

Do you have any mode detailed information like logs?

**Comment by atomsymbol** [comment] 2021-09-12 16:19
> Do you have any more detailed information like logs?

There are no warning messages in `~/.chia/mainnet/log/debug.log` and no messages in gui's console.

**Comment by jack60612** [comment] 2021-09-12 16:29
> > Do you have any more detailed information like logs?
> 
> There are no warning messages in `~/.chia/mainnet/log/debug.log` and no messages in gui's console.

i was able to reproduce it

**Comment by jack60612** [comment] 2021-09-12 16:29
thanks!

**Comment by jack60612** [comment] 2021-09-13 01:21
@atomsymbol I just did a lot of patching and bug fixes for the gui. I would just run the gui on latest for now until i have a chance to fix the api requests

**Comment by jcteng** [comment] 2021-09-14 04:35
did branch removed get_farmed_amount routing in get_wallet_balance 
![image](https://user-images.githubusercontent.com/14208527/133195583-7e6874d9-d250-41ce-a91f-b778bb1d1f26.png)

add it back should be fine

**Comment by jack60612** [comment] 2021-09-14 10:19
Ya I'm working on it but I'm waiting for my current pull to get submitted

**Comment by weaklysubjective** [comment] 2021-09-14 15:32
Adding to the ticket : experiencing same problem, spinners never resolve. chia version : 1.2.6.dev33.
Thanks

**Comment by jack60612** [comment] 2021-09-14 18:41
> Adding to the ticket : experiencing same problem, spinners never resolve. chia version : 1.2.6.dev33.
> Thanks

we know exactly what the issue is but it isnt going to be fixed until 1.2.7

**Comment by jack60612** [comment] 2021-09-14 18:41
> Adding to the ticket : experiencing same problem, spinners never resolve. chia version : 1.2.6.dev33.
> Thanks

just use latest for now

**Comment by jack60612** [comment] 2021-09-14 18:42
we have a bunch of changes coming so we are just focusing on those for now

**Comment by weaklysubjective** [comment] 2021-09-14 18:52
That's fine. No rush here.

**Comment by seeden** [comment] 2021-09-20 18:20
Loading on the farm page is fixed via https://github.com/Chia-Network/chia-blockchain-gui/pull/547

**Comment by seeden** [comment] 2021-09-21 08:08
Merged, I am closing this issue

**Closed by seeden** 2021-09-21 08:08 UTC
Labels: PR ready
