### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'walletKeyTheme')

### ISSUE THREAD

**Issue by wobblewoo** [Chia-Network/chia-blockchain-gui#2025] opened 2023-08-24 19:31 UTC
### What happened?

clicked on 'contacts' after upgrading to v2

### Version

2.0.0

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Cannot read properties of undefined (reading 'walletKeyTheme')

URL
#/dashboard/addressbook

Stacktrace
at webpack://@chia-network/gui/src/components/addressbook/MyContact.tsx:41:51 keyEntries.push
at webpack://@chia-network/gui/src/components/addressbook/MyContact.tsx:39:17 keyEntries.push
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:262:358 fk
at webpack://node_modules/scheduler/cjs/scheduler.production.min.js:18:342 unstable_next
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:122:324 eg
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:261:307 ek
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:261:214 ek
at webpack://node_modules/scheduler/cjs/scheduler.production.min.js:16:223 V
at webpack://node_modules/scheduler/cjs/scheduler.production.min.js:12:345 k
```

**Comment by paninaro** [comment] 2023-08-29 00:43
This issue is covered in the release notes for 2.0.0: https://github.com/Chia-Network/chia-blockchain/releases/tag/2.0.0

See:

- The GUI crashes when clicking on Contacts
   * Workaround: Log out of the wallet, and log back in

A fix has been merged and will be in the next release: https://github.com/Chia-Network/chia-blockchain-gui/pull/2024

Closing as a dupe of #2023

**Closed by paninaro** 2023-08-29 00:43 UTC
Labels: bug
