### ISSUE TITLE
[Bug] Issue with NFTs not showing

### ISSUE THREAD

**Issue by Nikonikolov1** [Chia-Network/chia-blockchain-gui#1510] opened 2023-02-27 12:18 UTC
### What happened?

after installing version 1.7.0, all NFTs disappeared
what to do?

### Version

1.7.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by MumfMeisterT** [comment] 2023-03-02 18:03
This is a duplicate of #1493 - Transferring this issue to `chia-blockchain-gui` repo, referencing this ticket, & closing.

This is a default setting updated in 1.7.0 but will be corrected soon. For now, please go to the GUI and try these two steps below.  
1. Go to "Settings" and "NFT"
2. Disable "Hide objectionable content"

**Closed by MumfMeisterT** 2023-03-02 18:03 UTC
Labels: bug

**Comment by L4bb3rs** [comment] 2023-03-02 18:17
The issue isn't the default. But the NFT not being objectable
