### ISSUE TITLE
[BUG] (0 , o.useLocalStorage) is not a function

### ISSUE THREAD

**Issue by trgarrett** [Chia-Network/chia-blockchain-gui#1116] opened 2022-10-27 19:03 UTC
### What happened?

Installed 1.6.1rc3
Tried to open NFTs tab

<img width="881" alt="image" src="https://user-images.githubusercontent.com/36970034/198376550-759933fc-2fa3-4c07-86c5-72733263e701.png">

### Version

1.6.1rc3

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
(0 , o.useLocalStorage) is not a function

URL
#/dashboard/nfts

Stacktrace
at webpack://@chia/gui/src/hooks/useNFTMetadata.ts:16:60 useNFTsMetadata
at webpack://@chia/gui/src/components/nfts/gallery/NFTGallery.tsx:52:26 NFTGallery
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:157:136 Ch
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:267:459 b?b.sibling:null}I
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:346 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:277 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:137 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:243:162 Lj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:123:114 jg
at webpack://@chia/gui/node_modules/scheduler/cjs/scheduler.production.min.js:18:342 unstable_next
```

**Comment by emlowe** [comment] 2022-10-27 19:50
duplicate of #1111 - fixed in RC4 - will be out soon

**Closed by emlowe** 2022-10-27 19:50 UTC
Labels: bug
