### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by sergomcs** [Chia-Network/chia-blockchain-gui#1388] opened 2023-01-31 09:06 UTC
### What happened?

The wallet stopped showing NFT and all offers for sale disappeared somewhere, they are not displayed in the wallet, but they are valid. I leave the wallet and go back, writes an error (screenshot).
<img width="1259" alt="Снимок экрана 2023-01-31 в 11 59 53" src="https://user-images.githubusercontent.com/121635076/215715991-1ead37f2-57ba-4a4b-8030-b06d49845cc6.png">
<img width="1440" alt="Снимок экрана 2023-01-31 в 11 59 34" src="https://user-images.githubusercontent.com/121635076/215716265-72ce672f-b029-4dac-834c-16563a4b1510.png">

### Version

1.6.2

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Cannot read properties of undefined (reading 'map')

URL
#/dashboard/offers/manage

Stacktrace
at webpack://@chia-network/gui/src/hooks/useAssetIdName.ts:28:12 AssetIdMapEntry>
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:168:376 $h
at webpack://@chia-network/gui/node_modules/react/cjs/react.production.min.js:23:112 useLayoutEffect
at webpack://@chia-network/gui/src/hooks/useAssetIdName.ts:20:54 useAssetIdName
at webpack://@chia-network/gui/src/hooks/useSaveOfferFile.ts:14:30 useSaveOfferFile
at webpack://@chia-network/gui/src/components/offers/OfferManager.tsx:509:22 CreateOffer
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:157:136 Ch
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:180:153 oi
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:269:342 a=b.pendingProps;f=e._init;e=f(e._payload);b.type=e;f=b.tag=hk(e);a=lg(e,a);switch
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:346 Pj
```

**Comment by paninaro** [comment] 2023-02-03 18:18
Dupe of #1313. This has been fixed by PR https://github.com/Chia-Network/chia-blockchain-gui/pull/1330 slated for the 1.7.0 release

**Closed by paninaro** 2023-02-03 18:18 UTC
Labels: bug
