### ISSUE TITLE
[BUG] "undefined" is not valid JSON

### ISSUE THREAD

**Issue by paulhainsworth-chia** [Chia-Network/chia-blockchain-gui#1419] opened 2023-02-03 04:44 UTC
### What happened?

Click on "Offer Accepted" in Transaction history in GUI.

Outcome:  "Something went wrong" error displayed. 

Resolution: click reload appliaction

Reproduced: 100% 

### Version

1.7.0rc5-dev21

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
"undefined" is not valid JSON

URL
#/dashboard/offers/view

Stacktrace
at webpack://@chia-network/gui/src/components/offers2/OfferBuilderViewer.tsx:68:36 useEffect(
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:172:114 useLayoutEffect
at webpack://@chia-network/gui/node_modules/react/cjs/react.production.min.js:23:112 useLayoutEffect
at webpack://@chia-network/gui/src/components/offers2/OfferBuilderViewer.tsx:67:27 useEffect(
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:157:136 Ch
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:267:459 b?b.sibling:null}I
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:346 Pj
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:277 Pj
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:137 Pj
```

**Comment by paninaro** [comment] 2023-02-03 18:14
Dupe of #1418

**Closed by paninaro** 2023-02-03 18:14 UTC
Labels: bug, 1.7.0
