### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'validTimes')

### ISSUE THREAD

**Issue by Ealrann** [Chia-Network/chia-blockchain-gui#2209] opened 2023-10-22 12:13 UTC
### What happened?

Hello, Tibet swap sent me an offer with wallet connect, and I wanted to preview the offer but it failed. The gui proposed me to report this issue.

The offer was to sell CAT for XCH.

### Version

2.1.1

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Cannot read properties of undefined (reading 'validTimes')

URL
#/dashboard/wallets/15

Stacktrace
at webpack://@chia-network/gui/src/components/offers2/OfferBuilderViewer.tsx:86:69 submit
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:167:136 Xh
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:193:56 Zi
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:294:274 f,b.memoizedState=f,b.flags&256){e=Ki(Error(p(423)),b);b=mj
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:280:388 uj
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:280:319 uj
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:280:179 uj
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:271:87 Ok
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:273:299 Dk
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:127:104 jg
```

**Comment by paninaro** [comment] 2023-10-25 18:39
Dupe of https://github.com/Chia-Network/chia-blockchain-gui/issues/2200, fixed by https://github.com/Chia-Network/chia-blockchain-gui/pull/2201

**Closed by paninaro** 2023-10-25 18:39 UTC
Labels: bug
