### ISSUE TITLE
[Bug] dApp Doesn't Reflect Disconnection

### ISSUE THREAD

**Issue by Rigidity** [Chia-Network/chia-blockchain-gui#1697] opened 2023-04-23 21:14 UTC
### What happened?

When you disconnect an app from the WalletConnect menu, the app pretends as if it's still connected. If you make a request it will fail as you'd expect, but the session remains. Additionally, if you reload the page, the example app and similar code based on WalletConnect's examples and APIs will reconnect to the old session from localStorage. Even though the app has been disconnected from the wallet GUI, it keeps creating the session without any error. Only when you go to make the request does it create an error.

The expected behavior here is that it automatically drops the session when you disconnect it, and never attempts to recreate it. You should need to connect to the wallet again from scratch. Currently the only way to fix this is to manually clear the localStorage and/or disconnect the app from the client side.

Separately, when you disconnect from the app side rather than the wallet, you should be able to repair with the wallet when you reload the page. Instead, you can see the pairings as you would expect, but when clicking on the pairing list, nothing happens. You simply can't reconnect to an old pairing. For my purposes I decided this functionality isn't especially useful, so I decided to ignore that and delete the pairing modal entirely.

### Version

1.8.0-rc1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by paninaro** [comment] 2023-04-24 18:31
@Rigidity this seems like a dupe of https://github.com/Chia-Network/chia-blockchain-gui/issues/1681 though in this case you're disconnecting from the dapp instead of the Chia GUI. Is that accurate?

**Comment by paninaro** [comment] 2023-04-28 23:50
@Rigidity can you give rc4 a try? Disconnecting a dapp from the Chia GUI seems to be working correctly for me.

**Comment by paninaro** [comment] 2023-05-01 16:31
This is working for me. Closing for now.

**Comment by Rigidity** [comment] 2023-05-20 21:06
This is still an issue in 1.8.1. The issue is not that disconnecting a dApp in the GUI fails, but rather that the dApp doesn't recognize that it has been disconnected when you do so. When you reload the page it will happily load the existing session even though it should have been closed by the GUI. Any commands you attempt to use while it's in this state will simply return "Invalid Request".

This is reproducible [using our example dApp](https://github.com/Chia-Network/chia-wallet-connect-dapp-test) and the workaround is to clear localStorage, which isn't user friendly.

**Comment by paninaro** [comment] 2023-06-08 23:23
Addressed by PR https://github.com/Chia-Network/chia-blockchain-gui/pull/1816

**Closed by paninaro** 2023-06-08 23:23 UTC
Labels: bug, 1.8.1
