### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'dark')

### ISSUE THREAD

**Issue by Lowestofttim** [Chia-Network/chia-blockchain-gui#738] opened 2022-05-17 16:13 UTC
### What happened?

When logging out of the wallet only gui and trying to either create a new set of keys or log in with a different set of words I recieve this error.

Wallet is fully synced

I can log back into original wallet fine.

### Version

1.3.5

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Cannot read properties of undefined (reading 'dark')

URL
#/

Stacktrace
at webpack://@chia/gui/node_modules/@mui/material/Button/Button.js:101:53 dark
at webpack://@chia/gui/node_modules/@mui/system/esm/createStyled.js:191:17 Array(numOfCustomFnsApplied).fill
at webpack://@chia/src/utils/flatten.js:68:21 isStatelessFunction
at webpack://@chia/src/models/ComponentStyle.js:91:28 phash
at webpack://@chia/src/models/StyledComponent.js:87:21 useInjectedStyle<T>
at webpack://@chia/src/models/StyledComponent.js:126:4 componentStyle
at webpack://@chia/src/models/StyledComponent.js:245:27 forwardRef
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:157:136 Ch
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:176:259 useOpaqueIdentifier
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:271:399 d=b.pendingProps;e=b.memoizedState;e=null!==e?e.element:null;yg(a,b);Cg(b,d,null,c);d=b.memoizedState.element;if(d===e)sh(),b=hi(a,b,c);else{e=b.stateNode;if(f=e.hydrate)kh=rf(b.stateNode.containerInfo.firstChild),jh=b,f=lh=!0;if
```

**Comment by seeden** [comment] 2022-05-17 22:54
Thank you for detailed explanation how to reproduce it. I will fix it

**Comment by CoderArgentina** [comment] 2022-06-28 23:46
I have the same problem, and cannot open it in any way, i completely uninstalled chia and have the same problem after reinstall, how can i set it to light theme?

**Comment by jurepetrovic** [comment] 2022-07-21 09:17
> e

How did you set the password at this stage?

**Comment by raid5** [comment] 2022-07-27 16:07
I'm experiencing this same bug. Looks like there are a TON of dupe issues being created.

**Comment by seeden** [comment] 2022-07-27 16:13
Thanks for the report @raid5. Would you be able to attach a screen recording of the issue, or screenshots if you can't record a video? Any other details that you can provide would be appreciated.

**Comment by seeden** [comment] 2022-07-27 16:23
@raid5 I am sorry, but I am not able to reproduce it on my computer but I prepared a fix which should fix it. Will you try it when I prepare PR?

**Comment by seeden** [comment] 2022-07-27 16:57
It looks like a pure windows issue. I am installing virtual machine and try to reproduce it.

**Comment by raid5** [comment] 2022-07-27 17:41
I'm on a Mac and hit this issue, so I don't believe it is Windows only. I'm happy to test out your fix, just not really sure how. I would have to build it from source after pulling down your PR? I haven't done any dev work against this repo yet.

**Comment by seeden** [comment] 2022-07-27 17:55
@raid5 ohhh, that is odd. I tried to simulate it on my mac 100 times and no luck

**Comment by jurepetrovic** [comment] 2022-07-28 12:27
No, it was not Windows issue. It happened to me on Debian 10. 
I migrated keys from old version from CLI and then the GUI worked. 
But it's a dirty workaround.

**Comment by seeden** [comment] 2022-08-15 12:54
Probably fixed via https://github.com/Chia-Network/chia-blockchain-gui/pull/922. Can you try it?

**Closed** 2022-09-07 16:00 UTC
Labels: bug, PR ready
